[package]
name = "piicleaner"
version = "0.4.2"
edition = "2021"

[lib]
name = "piicleaner"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
rayon = "1.10"
regex = "1.11"

[build-dependencies]
pyo3-build-config = "0.24"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "benchmarks"
harness = false
