name: Test Release

on:
  push:
    tags:
      - 'v*-test*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]  # Just test on x86_64 for speed
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: --release --out dist --find-interpreter
        sccache: 'true'
        manylinux: auto
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux-${{ matrix.target }}
        path: dist

  test-release:
    name: Test Release to TestPyPI
    runs-on: ubuntu-latest
    needs: [linux]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/piicleaner
    permissions:
      id-token: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: dist
        merge-multiple: true
    - name: Publish to TestPyPI
      uses: PyPA/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/